pom.xml
Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>
=> Changed groupId and artifactId. Fixes #10 (EE4J)

pom.xml
Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>
=> Changed groupId and artifactId. Fixes #10 (master)

pom.xml
- plugin versions moved to pluginManagement section
- plugin versions updated
- parent updated to org.eclipse.ee4j:project:1.0.2
Incorporating IP team feedback (PR#7)
=> Project pom.xml prepared for release job.

pom.xml
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
=> CA release

pom.xml
Fixes #23 
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>
=> fixes #23: bundle symbolic name should match artifactId

pom.xml
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>
=> version should be set to 1.3.4-SNAPSHOT

pom.xml
Branch 1.3.3 can be deleted after merge.
=> Merge release information for 1.3.3 into EE4J_8 branch.

pom.xml
Branch 1.3.3 can be deleted after merge.
=> Merge release information for 1.3.4 into EE4J_8 branch.

pom.xml
plugin is already configured in parent
=> Remove source plugin

pom.xml, spec/pom.xml
Fixes #49. As 1.3.4 has been released this upgrades the version number.
=> Set version to 1.3.5-SNAPSHOT

.gitignore, api/src/main/javadoc/doc-files/EFSL.html
=> Javadoc license

api/pom.xml, pom.xml, spec/pom.xml
=> Update parent pom

api/pom.xml, spec/src/main/asciidoc/license-efsl.adoc
=> Eclipse copyright

pom.xml
=> Upgrading parent to 1.0.6

spec/src/main/asciidoc/license-efsl.adoc, spec/src/main/asciidoc/spec.adoc
=> Jakartified spec

CONTRIBUTING.md
=> #74: Update CONTRIBUTING.md for Specification Project's repositories

README.md
Related to https://github.com/eclipse-ee4j/common-annotations-api/issues/68
Signed-off-by: Werner Keil <werner.keil@gmx.net>
=> Updated README with correct module name

api/pom.xml, spec/pom.xml
Version changed to 2.1-SNAPSHOT
upgraded to newer parent artifact
Asciidoc plugin updated to the latest version
=> Version changed to 2.1.0-SNAPSHOT

api/pom.xml, spec/src/main/asciidoc/license-efsl.adoc
=> Copyright year fixes

api/pom.xml
=> use release 11 to comply with the plan

api/pom.xml
=> make sure built javadoc contains year 2024,

api/pom.xml
this should be merged through _Create a merge commit_ before #128
=> 3.0.0 branch
